INSERT INTO RANK
VALUES(SYS_GUID(), '사원');

INSERT INTO RANK
VALUES(SYS_GUID(), '인턴');

INSERT INTO RANK
VALUES(SYS_GUID(), '주임');

INSERT INTO RANK
VALUES(SYS_GUID(), '대리');

INSERT INTO RANK
VALUES(SYS_GUID(), '과장');

INSERT INTO RANK
VALUES(SYS_GUID(), '차장');

INSERT INTO RANK
VALUES(SYS_GUID(), '전무');

INSERT INTO RANK
VALUES(SYS_GUID(), '이사');

INSERT INTO RANK
VALUES(SYS_GUID(), 'CEO');

COMMIT;