INSERT INTO DEPARTMENT
VALUES(SYS_GUID(), '개발부');

INSERT INTO DEPARTMENT
VALUES(SYS_GUID(), '영업부');

INSERT INTO DEPARTMENT
VALUES(SYS_GUID(), '무역부');


INSERT INTO DEPARTMENT
VALUES(SYS_GUID(), '경리부');


INSERT INTO DEPARTMENT
VALUES(SYS_GUID(), '아무것도안하는부');

COMMIT;